name: dart_fsm
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.0

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  collection: ^1.18.0
  test: ">=1.24.0 <1.25.2"

dev_dependencies:
  lints: ^3.0.0
  very_good_analysis: ^5.1.0
