name: dart_fsm
description: A package for implementing finite state machines in Dart.
version: 1.1.1
homepage: https://team-lab.com
repository: https://github.com/team-lab/dart_fsm

environment:
  sdk: ">=3.4.0 <4.0.0"

# Add regular dependencies here.
dependencies:
  collection: ^1.18.0
  meta: ^1.15.0
  test: ">=1.24.0 <=1.25.8"

dev_dependencies:
  lints: ^3.0.0
  very_good_analysis: ^5.1.0
